### PR TITLE
Replaced ECKey with AsymmetricJWK to get PublickKey

### LINKED ISSUE #186: KeyBindingJwt should be verified with RSA or EC keys
Currently KeyBindingJwt can only be verified with ECKey.

https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/blob/6fd337bd38c70f4b42db9b6c70171f931efab71f/src/main/kotlin/eu/europa/ec/eudi/sdjwt/NimbusIntegration.kt#L123

If `holderPubKey` is RSA it will throw class-cast exception.

### PR DESCRIPTION
**Pull request by ydanneg**
Fixes #186

### CODE REVIEW

**Review by babisRoutis — CHANGES_REQUESTED** [review]
@ydanneg Perhaps the `holderPubKey` parameter should be declared of type `AsymmetricJWK`.
Can you please change the type (using an import alias of NimbusAsymmetricJWK) ?

**Comment by babisRoutis** [comment]
@ydanneg Also please run `spotlessApply` to format code

**Comment by babisRoutis** [comment]
@ydanneg Please note I am on Easter vacations. Will check this next week.

**Comment by babisRoutis** [comment]
@ydanneg On second thought changing the parameter type will lead to some additional cascading changes.
I can push to your branch the changes if it is ok with you.

**Comment by ydanneg** [comment]
> @ydanneg On second thought changing the parameter type will lead to some additional cascading changes.
> I can push to your branch the changes if it is ok with you.

Absolutely fine with it! :)

**Pull request merged**
